# -*- coding: utf-8 -*-
# Author: Tyler Landle <tlandle3@gatech.edu>
# License: TDG-Attribution-NonCommercial-NoDistrib

"""
Multi-ego (4 vehicles) variant of openscenario_3_edge_late_fusion.
Generated by generate_multi_ego_scenario.py.

Ego 1 is the ScenarioRunner hero. Egos 2-4 are self-spawned by
VehicleManager from their spawn_position config.
"""

import time
from multiprocessing import Process
import asyncio

import carla
import scenario_runner.scenario_runner as sr
import ecav.scenario_testing.utils.sim_api as sim_api
from ecav.core.common.cav_world import CavWorld
from ecav.scenario_testing.evaluations.evaluate_manager import \
    EvaluationManager
from ecav.scenario_testing.utils.yaml_utils import add_current_time

import ecloud_pb2 as ecloud

MAX_STEP = 300
SCENARIO_NAME = 'openscenario_3_edge_late_fusion_4ego'
scenario_runner = None


def exec_scenario_runner(scenario_params):
    scenario_runner = sr.ScenarioRunner(scenario_params.scenario_runner)
    scenario_runner.run()
    scenario_runner.destroy()


def run_vehicle(opt, scenario_params):
    assert opt.distributed
    try:
        scenario_runner = sr.ScenarioRunner(scenario_params.scenario_runner)
        scenario_runner.run()
        scenario_runner.destroy()
    except Exception as e:
        print(f"vehicle_index: {scenario_params.scenario_runner.vehicle_index}")
        raise e


def run_scenario(opt, scenario_params):
    global scenario_runner
    cav_world = None
    scenario_manager = None
    eval_manager = None
    sr_process = None
    edge_list = []
    step = 0

    try:
        scenario_params = add_current_time(scenario_params)

        cav_world = CavWorld(
            apply_ml=opt.apply_ml,
            config=scenario_params,
            litserve=getattr(opt, 'litserve', False)
        )

        scenario_manager = sim_api.ScenarioManager(
            scenario_params,
            opt.apply_ml,
            opt.version,
            town=scenario_params.scenario_runner.town,
            cav_world=cav_world,
            distributed=opt.distributed
        )

        if opt.distributed:
            asyncio.get_event_loop().run_until_complete(scenario_manager.run_comms())
        else:
            sr_process = Process(target=exec_scenario_runner,
                                 args=(scenario_params,))
            sr_process.start()

        world = scenario_manager.world
        ego_vehicle = None
        num_actors = 0

        while ego_vehicle is None or num_actors < scenario_params.scenario_runner.num_actors:
            print("Waiting for the actors")
            time.sleep(2)
            vehicles = world.get_actors().filter('vehicle.*')
            walkers = world.get_actors().filter('walker.*')
            for vehicle in vehicles:
                if vehicle.attributes['role_name'] == 'hero' and ego_vehicle is None:
                    print("Ego 1 (hero) found")
                    ego_vehicle = vehicle
            num_actors = len(vehicles) + len(walkers)
        print(f'Found all {num_actors} actors')

        world_dt = scenario_params['world']['fixed_delta_seconds']
        edge_dt = scenario_params['edge_base']['edge_dt']
        assert edge_dt % world_dt == 0

        try:
            edge_list = scenario_manager.create_edge_manager_from_scenario_runner(
                application=['edge'],
                edge_dt=edge_dt,
                world_dt=world_dt,
                ego_vehicle=ego_vehicle,
                other_vehicles=[],
            )
        except Exception:
            import traceback, sys
            traceback.print_exc()
            sys.exit(1)

        n_egos = len(edge_list[0].vehicle_manager_list) if edge_list else 0
        print(f"[MULTI-EGO] Edge managing {n_egos} ego vehicles")
        for i, vm in enumerate(edge_list[0].vehicle_manager_list):
            loc = vm.vehicle.get_transform().location
            print(f"  cav{i+1}: carla_id={vm.vehicle.id}, "
                  f"pos=({loc.x:.1f}, {loc.y:.1f}, {loc.z:.1f})")
            # Non-hero egos should not sys.exit(0) on destination arrival
            if i > 0 and hasattr(vm.agent, '_exit_on_destination'):
                vm.agent._exit_on_destination = False

        eval_manager = EvaluationManager(
            scenario_manager.cav_world,
            script_name=SCENARIO_NAME,
            scenario_params=scenario_params,
            current_time=scenario_params['current_time'],
            output_dir=opt.output_dir
        )

        spectator = ego_vehicle.get_world().get_spectator()
        spectator_altitude = 160
        spectator_bird_pitch = -90

        flag = True
        while flag:
            if opt.distributed:
                command = ecloud.Command.PULL_OBJECTS_AND_TICK if step > 0 else ecloud.Command.TICK
                flag = scenario_manager.broadcast_message(command)
                scenario_manager.tick_world()
            else:
                scenario_manager.tick()

            if scenario_manager.all_vehicles_done:
                print(f"All vehicles reported done ({scenario_manager.num_completed_vehicles}/{scenario_manager.vehicle_count}), ending simulation")
                break

            # Bird view centered on intersection
            view_transform = carla.Transform()
            view_transform.location = carla.Location(
                x=-78.0, y=128.0, z=spectator_altitude)
            view_transform.rotation.pitch = spectator_bird_pitch
            spectator.set_transform(view_transform)

            for edge in edge_list:
                serialized_predictions = edge.run_step(step)
                if opt.distributed and serialized_predictions is not None:
                    scenario_manager.push_edge_objects(serialized_predictions)

            step += 1
            if step >= MAX_STEP:
                print("Reached maximum step limit, exiting")
                break

            time.sleep(0.001)

    except SystemExit as e:
        print(f"Caught SystemExit({e.code}) — proceeding to evaluation/cleanup")

    except Exception as e:
        print(f"Caught {type(e).__name__}: {e} — proceeding to evaluation/cleanup")
        import traceback
        print(traceback.format_exc())

    finally:
        if sr_process is not None:
            sr_process.terminate()
            sr_process.join(timeout=5)

        if scenario_runner is not None:
            scenario_runner.destroy()

        for edge in edge_list:
            for i, vm in enumerate(edge.vehicle_manager_list):
                for vid, step_number in vm.vehicles_detected.items():
                    print(f"VID: {vm.vehicle.id} found VID {vid} at step {step_number}")

        if opt.distributed and scenario_manager is not None:
            scenario_manager.end()

        if eval_manager is not None:
            eval_manager.evaluate()

        if scenario_manager is not None:
            scenario_manager.close()
