// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ecloud.proto

#include "ecloud.pb.h"
#include "ecloud.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace ecloud {

static const char* Ecloud_method_names[] = {
  "/ecloud.Ecloud/PushTick",
  "/ecloud.Ecloud/Client_SendUpdate",
  "/ecloud.Ecloud/Client_RegisterVehicle",
  "/ecloud.Ecloud/Client_GetWaypoints",
  "/ecloud.Ecloud/Client_GetObjects",
  "/ecloud.Ecloud/Server_DoTick",
  "/ecloud.Ecloud/Server_StartScenario",
  "/ecloud.Ecloud/Server_EndScenario",
  "/ecloud.Ecloud/Server_GetVehicleUpdates",
  "/ecloud.Ecloud/Server_PushEdgeWaypoints",
};

std::unique_ptr< Ecloud::Stub> Ecloud::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Ecloud::Stub> stub(new Ecloud::Stub(channel, options));
  return stub;
}

Ecloud::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_PushTick_(Ecloud_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Client_SendUpdate_(Ecloud_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Client_RegisterVehicle_(Ecloud_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Client_GetWaypoints_(Ecloud_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Client_GetObjects_(Ecloud_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Server_DoTick_(Ecloud_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Server_StartScenario_(Ecloud_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Server_EndScenario_(Ecloud_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Server_GetVehicleUpdates_(Ecloud_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Server_PushEdgeWaypoints_(Ecloud_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Ecloud::Stub::PushTick(::grpc::ClientContext* context, const ::ecloud::Tick& request, ::ecloud::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::Tick, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PushTick_, context, request, response);
}

void Ecloud::Stub::async::PushTick(::grpc::ClientContext* context, const ::ecloud::Tick* request, ::ecloud::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::Tick, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushTick_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::PushTick(::grpc::ClientContext* context, const ::ecloud::Tick* request, ::ecloud::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PushTick_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::PrepareAsyncPushTickRaw(::grpc::ClientContext* context, const ::ecloud::Tick& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::Empty, ::ecloud::Tick, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PushTick_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::AsyncPushTickRaw(::grpc::ClientContext* context, const ::ecloud::Tick& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPushTickRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Client_SendUpdate(::grpc::ClientContext* context, const ::ecloud::VehicleUpdate& request, ::ecloud::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::VehicleUpdate, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Client_SendUpdate_, context, request, response);
}

void Ecloud::Stub::async::Client_SendUpdate(::grpc::ClientContext* context, const ::ecloud::VehicleUpdate* request, ::ecloud::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::VehicleUpdate, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Client_SendUpdate_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Client_SendUpdate(::grpc::ClientContext* context, const ::ecloud::VehicleUpdate* request, ::ecloud::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Client_SendUpdate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::PrepareAsyncClient_SendUpdateRaw(::grpc::ClientContext* context, const ::ecloud::VehicleUpdate& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::Empty, ::ecloud::VehicleUpdate, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Client_SendUpdate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::AsyncClient_SendUpdateRaw(::grpc::ClientContext* context, const ::ecloud::VehicleUpdate& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClient_SendUpdateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Client_RegisterVehicle(::grpc::ClientContext* context, const ::ecloud::RegistrationInfo& request, ::ecloud::SimulationInfo* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::RegistrationInfo, ::ecloud::SimulationInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Client_RegisterVehicle_, context, request, response);
}

void Ecloud::Stub::async::Client_RegisterVehicle(::grpc::ClientContext* context, const ::ecloud::RegistrationInfo* request, ::ecloud::SimulationInfo* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::RegistrationInfo, ::ecloud::SimulationInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Client_RegisterVehicle_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Client_RegisterVehicle(::grpc::ClientContext* context, const ::ecloud::RegistrationInfo* request, ::ecloud::SimulationInfo* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Client_RegisterVehicle_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::SimulationInfo>* Ecloud::Stub::PrepareAsyncClient_RegisterVehicleRaw(::grpc::ClientContext* context, const ::ecloud::RegistrationInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::SimulationInfo, ::ecloud::RegistrationInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Client_RegisterVehicle_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::SimulationInfo>* Ecloud::Stub::AsyncClient_RegisterVehicleRaw(::grpc::ClientContext* context, const ::ecloud::RegistrationInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClient_RegisterVehicleRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Client_GetWaypoints(::grpc::ClientContext* context, const ::ecloud::WaypointRequest& request, ::ecloud::WaypointBuffer* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::WaypointRequest, ::ecloud::WaypointBuffer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Client_GetWaypoints_, context, request, response);
}

void Ecloud::Stub::async::Client_GetWaypoints(::grpc::ClientContext* context, const ::ecloud::WaypointRequest* request, ::ecloud::WaypointBuffer* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::WaypointRequest, ::ecloud::WaypointBuffer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Client_GetWaypoints_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Client_GetWaypoints(::grpc::ClientContext* context, const ::ecloud::WaypointRequest* request, ::ecloud::WaypointBuffer* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Client_GetWaypoints_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::WaypointBuffer>* Ecloud::Stub::PrepareAsyncClient_GetWaypointsRaw(::grpc::ClientContext* context, const ::ecloud::WaypointRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::WaypointBuffer, ::ecloud::WaypointRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Client_GetWaypoints_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::WaypointBuffer>* Ecloud::Stub::AsyncClient_GetWaypointsRaw(::grpc::ClientContext* context, const ::ecloud::WaypointRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClient_GetWaypointsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Client_GetObjects(::grpc::ClientContext* context, const ::ecloud::ObjectRequest& request, ::ecloud::ObjectBuffer* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::ObjectRequest, ::ecloud::ObjectBuffer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Client_GetObjects_, context, request, response);
}

void Ecloud::Stub::async::Client_GetObjects(::grpc::ClientContext* context, const ::ecloud::ObjectRequest* request, ::ecloud::ObjectBuffer* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::ObjectRequest, ::ecloud::ObjectBuffer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Client_GetObjects_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Client_GetObjects(::grpc::ClientContext* context, const ::ecloud::ObjectRequest* request, ::ecloud::ObjectBuffer* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Client_GetObjects_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::ObjectBuffer>* Ecloud::Stub::PrepareAsyncClient_GetObjectsRaw(::grpc::ClientContext* context, const ::ecloud::ObjectRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::ObjectBuffer, ::ecloud::ObjectRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Client_GetObjects_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::ObjectBuffer>* Ecloud::Stub::AsyncClient_GetObjectsRaw(::grpc::ClientContext* context, const ::ecloud::ObjectRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncClient_GetObjectsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Server_DoTick(::grpc::ClientContext* context, const ::ecloud::Tick& request, ::ecloud::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::Tick, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Server_DoTick_, context, request, response);
}

void Ecloud::Stub::async::Server_DoTick(::grpc::ClientContext* context, const ::ecloud::Tick* request, ::ecloud::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::Tick, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_DoTick_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Server_DoTick(::grpc::ClientContext* context, const ::ecloud::Tick* request, ::ecloud::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_DoTick_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::PrepareAsyncServer_DoTickRaw(::grpc::ClientContext* context, const ::ecloud::Tick& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::Empty, ::ecloud::Tick, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Server_DoTick_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::AsyncServer_DoTickRaw(::grpc::ClientContext* context, const ::ecloud::Tick& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncServer_DoTickRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Server_StartScenario(::grpc::ClientContext* context, const ::ecloud::SimulationInfo& request, ::ecloud::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::SimulationInfo, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Server_StartScenario_, context, request, response);
}

void Ecloud::Stub::async::Server_StartScenario(::grpc::ClientContext* context, const ::ecloud::SimulationInfo* request, ::ecloud::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::SimulationInfo, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_StartScenario_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Server_StartScenario(::grpc::ClientContext* context, const ::ecloud::SimulationInfo* request, ::ecloud::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_StartScenario_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::PrepareAsyncServer_StartScenarioRaw(::grpc::ClientContext* context, const ::ecloud::SimulationInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::Empty, ::ecloud::SimulationInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Server_StartScenario_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::AsyncServer_StartScenarioRaw(::grpc::ClientContext* context, const ::ecloud::SimulationInfo& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncServer_StartScenarioRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Server_EndScenario(::grpc::ClientContext* context, const ::ecloud::Empty& request, ::ecloud::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::Empty, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Server_EndScenario_, context, request, response);
}

void Ecloud::Stub::async::Server_EndScenario(::grpc::ClientContext* context, const ::ecloud::Empty* request, ::ecloud::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::Empty, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_EndScenario_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Server_EndScenario(::grpc::ClientContext* context, const ::ecloud::Empty* request, ::ecloud::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_EndScenario_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::PrepareAsyncServer_EndScenarioRaw(::grpc::ClientContext* context, const ::ecloud::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::Empty, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Server_EndScenario_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::AsyncServer_EndScenarioRaw(::grpc::ClientContext* context, const ::ecloud::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncServer_EndScenarioRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Server_GetVehicleUpdates(::grpc::ClientContext* context, const ::ecloud::Empty& request, ::ecloud::EcloudResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::Empty, ::ecloud::EcloudResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Server_GetVehicleUpdates_, context, request, response);
}

void Ecloud::Stub::async::Server_GetVehicleUpdates(::grpc::ClientContext* context, const ::ecloud::Empty* request, ::ecloud::EcloudResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::Empty, ::ecloud::EcloudResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_GetVehicleUpdates_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Server_GetVehicleUpdates(::grpc::ClientContext* context, const ::ecloud::Empty* request, ::ecloud::EcloudResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_GetVehicleUpdates_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::EcloudResponse>* Ecloud::Stub::PrepareAsyncServer_GetVehicleUpdatesRaw(::grpc::ClientContext* context, const ::ecloud::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::EcloudResponse, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Server_GetVehicleUpdates_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::EcloudResponse>* Ecloud::Stub::AsyncServer_GetVehicleUpdatesRaw(::grpc::ClientContext* context, const ::ecloud::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncServer_GetVehicleUpdatesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Ecloud::Stub::Server_PushEdgeWaypoints(::grpc::ClientContext* context, const ::ecloud::EdgeWaypoints& request, ::ecloud::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ecloud::EdgeWaypoints, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Server_PushEdgeWaypoints_, context, request, response);
}

void Ecloud::Stub::async::Server_PushEdgeWaypoints(::grpc::ClientContext* context, const ::ecloud::EdgeWaypoints* request, ::ecloud::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ecloud::EdgeWaypoints, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_PushEdgeWaypoints_, context, request, response, std::move(f));
}

void Ecloud::Stub::async::Server_PushEdgeWaypoints(::grpc::ClientContext* context, const ::ecloud::EdgeWaypoints* request, ::ecloud::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Server_PushEdgeWaypoints_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::PrepareAsyncServer_PushEdgeWaypointsRaw(::grpc::ClientContext* context, const ::ecloud::EdgeWaypoints& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ecloud::Empty, ::ecloud::EdgeWaypoints, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Server_PushEdgeWaypoints_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ecloud::Empty>* Ecloud::Stub::AsyncServer_PushEdgeWaypointsRaw(::grpc::ClientContext* context, const ::ecloud::EdgeWaypoints& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncServer_PushEdgeWaypointsRaw(context, request, cq);
  result->StartCall();
  return result;
}

Ecloud::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::Tick, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::Tick* req,
             ::ecloud::Empty* resp) {
               return service->PushTick(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::VehicleUpdate, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::VehicleUpdate* req,
             ::ecloud::Empty* resp) {
               return service->Client_SendUpdate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::RegistrationInfo, ::ecloud::SimulationInfo, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::RegistrationInfo* req,
             ::ecloud::SimulationInfo* resp) {
               return service->Client_RegisterVehicle(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::WaypointRequest, ::ecloud::WaypointBuffer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::WaypointRequest* req,
             ::ecloud::WaypointBuffer* resp) {
               return service->Client_GetWaypoints(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::ObjectRequest, ::ecloud::ObjectBuffer, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::ObjectRequest* req,
             ::ecloud::ObjectBuffer* resp) {
               return service->Client_GetObjects(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::Tick, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::Tick* req,
             ::ecloud::Empty* resp) {
               return service->Server_DoTick(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::SimulationInfo, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::SimulationInfo* req,
             ::ecloud::Empty* resp) {
               return service->Server_StartScenario(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::Empty, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::Empty* req,
             ::ecloud::Empty* resp) {
               return service->Server_EndScenario(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::Empty, ::ecloud::EcloudResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::Empty* req,
             ::ecloud::EcloudResponse* resp) {
               return service->Server_GetVehicleUpdates(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Ecloud_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Ecloud::Service, ::ecloud::EdgeWaypoints, ::ecloud::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Ecloud::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ecloud::EdgeWaypoints* req,
             ::ecloud::Empty* resp) {
               return service->Server_PushEdgeWaypoints(ctx, req, resp);
             }, this)));
}

Ecloud::Service::~Service() {
}

::grpc::Status Ecloud::Service::PushTick(::grpc::ServerContext* context, const ::ecloud::Tick* request, ::ecloud::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Client_SendUpdate(::grpc::ServerContext* context, const ::ecloud::VehicleUpdate* request, ::ecloud::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Client_RegisterVehicle(::grpc::ServerContext* context, const ::ecloud::RegistrationInfo* request, ::ecloud::SimulationInfo* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Client_GetWaypoints(::grpc::ServerContext* context, const ::ecloud::WaypointRequest* request, ::ecloud::WaypointBuffer* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Client_GetObjects(::grpc::ServerContext* context, const ::ecloud::ObjectRequest* request, ::ecloud::ObjectBuffer* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Server_DoTick(::grpc::ServerContext* context, const ::ecloud::Tick* request, ::ecloud::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Server_StartScenario(::grpc::ServerContext* context, const ::ecloud::SimulationInfo* request, ::ecloud::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Server_EndScenario(::grpc::ServerContext* context, const ::ecloud::Empty* request, ::ecloud::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Server_GetVehicleUpdates(::grpc::ServerContext* context, const ::ecloud::Empty* request, ::ecloud::EcloudResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Ecloud::Service::Server_PushEdgeWaypoints(::grpc::ServerContext* context, const ::ecloud::EdgeWaypoints* request, ::ecloud::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ecloud

